POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "username": "kazemsad",
    "password": "kazem is sad"
}

###
POST http://localhost:3000/api/auth/signup 
content-type: application/json

{
    "username": "kazemsad2",
    "password": "kazem is very sad",
    "role_name": "user"
}

### 
GET http://localhost:3000/api/user

###
PUT http://localhost:3000/api/auth/make_admin/752110f4-bdbd-4f65-9b22-f3be4c6be779